### ISSUE TITLE
Portable/standalone version

### ISSUE THREAD

**Issue by sceadu37** [tim-de/tgrlib#11]
Most people in the KAG community don't know how to use python and may not want to install it just to run a single script. Creating an exe using pyinstaller or a similar tool, or setting up an easily distributable portable environment would make using these tools a lot more accessible

**Comment by tim-de** [comment]
Yeah, this is a really good consideration,  and a big reason that I wrote tgxpack in Go, as it compiles to static binary form. I am pretty sure there are tools to do similar things with python scripts, so I'll have a look into that

**Comment by sceadu37** [comment]
[pyinstaller ](https://pyinstaller.org/en/stable/index.html) seems quite easy to use. It needs a little customization to find data files (eg COLORS.INI) when packed to a standalone executable, but works out of the box when packing to a single folder

**Comment by sceadu37** [comment]
Just pushed a working version for compiling with pyinstaller. The downsides to this are a large .exe (~250MB) and a ~6s delay each time the exe is run, since it has to unpack itself each time. The alternative is for pyinstaller to pack everything into a folder which runs much quicker, but that also opens up more room for user error as the exe can't be moved without causing issues
