### ISSUE TITLE
Prevent extraneous padding pixels being written to line data

### ISSUE THREAD

**Issue by sceadu37** [tim-de/tgrlib#7]
When packing an image into a FRAM chunk, the transparent background pixels between the rightmost colored pixel and the right edge are being packed into each line. This doesn't prevent the file from being read correctly by the game, but it is unnecessary and a waste of space.
ecodeLine should be updated to skip writing when all remaining pixels in a line are background

**Comment by tim-de** [comment]
I am hoping to be able to resolve this with a check in `look_ahead()` to see if it's reached the end of a line, and has collected only transparent pixels

**Comment by tim-de** [comment]
This is fixed with latest version of tgrlib.py
